name: EAS Update Preview
on:
  push:
    branches: [prod]
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install --legacy-peer-deps
      - name: Publish update to production channel
        run: npx eas-cli update --branch production --message "CI update from prod"
      - name: Publish update to development channel
        run: npx eas-cli update --branch development --message "CI update from prod"